name: Publish Python Package to PyPI

# Trigger the workflow when a tag starting with 'v' is pushed
on:
  push:
    tags:
      - 'v*' # Matches v0.1.0, v1.0, v2.3.4 etc.

jobs:
  build:
    name: Build package distributions
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Use a specific version or a range appropriate for your package
          python-version: '3.12'

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build package (sdist + wheel)
        run: python -m build

      - name: Store the distribution packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions # Name for the artifact
          path: dist/ # Directory containing the built packages

  publish_pypi:
    name: Publish package to PyPI
    needs: [build] # Run this job only after 'build' job succeeds
    runs-on: ubuntu-latest

    # Define the environment for PyPI publishing
    environment:
      name: pypi # This name MUST match the environment configured in PyPI
      # Optional: Link to the PyPI project page in GitHub Deployments UI
      url: https://pypi.org/p/htmleval # *** Updated package name ***

    # Grant permission for the workflow to request an OpenID Connect (OIDC) token
    permissions:
      id-token: write # Required for Trusted Publishing

    steps:
      - name: Download distributions artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions # Must match the upload artifact name
          path: dist/

      - name: Publish package distributions to PyPI
        # Use the official PyPA action for publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        # No username/password needed due to Trusted Publishing!
        # The action automatically handles OIDC authentication.
